service: nestjs-serverless-graphql
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: GET
          path: /products
      - http:
          method: ANY
          path: '{proxy+}'